export const GET_ERRORS="GET_ERRORS";
export const GET_BANK_ACCOUNTS="GET_BANK_ACCOUNTS";
export const GET_BANK_ACCOUNT="GET_BANK_ACCOUNT";
export const CREATE_BANK_ACCOUNT="CREATE_BANK_ACCOUNT";
export const DELETE_BANK_ACCOUNT="DELETE_BANK_ACCOUNT";

export const GET_TRANSACTIONS="GET_TRANSACTIONS"
export const CREATE_TRANSACTION="CREATE_TRANSACTION"
